<?php 

//chiave = NOME_COLONNA
//valore = TIPO_COLONNA
return [
	"COLONNEDB" => [
		"NOME_COLONNA" => "TIPO_COLONNA"
	],
	"COLONNA_FOLDER_FILE_DA_ESTRARRE" => "",
	"COLONNA_FOLDER_FILE_ESTRATTO" => "",
	"COLONNA_FILE_DA_ESTRARRE" => "",
	"COLONNA_FILE_ESTRATTO" => "",
	"FILESYSTEM_DISK" => "",
];